spring:
  datasource:
    url: 'jdbc:sqlserver://code-split-server.database.windows.net:1433;database=Split Code;user=codesplit@code-split-server;password={split@2024};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;'
    username: codesplit@code-split-server
    password: split@2024


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect